name: dart_router_extended
description: Dart Router Extended expands on shelf and shelf_router to provide a more friendly web server routing capabilities.
version: 1.0.0
repository: https://github.com/ctrohin/dart_router_extended.git

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4


dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
